#!/bin/sh
set -eu
#:_______________________________________________________________________
#   ᛟ minim  |  Copyright (C) Ivan Mar (sOkam!)  |  GNU LGPLv3 or later  :
#:_______________________________________________________________________
## @fileoverview Dummy buildsystem. Temporary until confy rework
#________________________________________________________________|


#_______________________________________
# Folders
thisDir=$(pwd)
srcDir=$thisDir/src
binDir=$thisDir/bin
zigDir=$binDir/.zig
cacheDir=$binDir/.cache
testsDir=$srcDir/tests
#_______________________________________
# Zig Compiler Setup
Z=$zigDir/zig
target="-target x86_64-linux-gnu"
# libs=""
libs="-lc"
verb=""
# verb="--verbose-cc --verbose-link"
flags="-fPIE -fcompiler-rt $target $verb $libs"
cache="--cache-dir $cacheDir --global-cache-dir $cacheDir"
# Compiler Commands
tests()     { $Z test $srcDir/tests.zig; }
build()     { $Z build-exe $flags $cache -femit-bin=$2 $1; }
build_lib() { $Z build-lib $flags $cache -femit-bin=$2 $1; }
#_______________________________________



#_______________________________________
# Source Code Setup
src=$srcDir/M.zig
trg=$binDir/M

#_______________________________________
# Order to build
tests
build $src $trg
$trg

